---
title: "ALDEx2 Analysis for Differential Gene Abundance"
Author: Brooke M. Talbot
output: html_notebook
---

# Version of Code
This code is maintained by Brooke M. Talbot. This is part of the resubmission with Version 2.0 of the main analysis code and was updated last on 4/1/2024

# R Libraries and set up ##
These analyses were conducted using R version 4.2.1

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
library(devtools)
library(tibble)
library(dplyr)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(cowplot)

#devtools::install_github("ggloor/ALDEx_bioc")
library(ALDEx2)


```

# ALDEx2 Analysis
## By Class - Data 
```{r}

## Reading in Data - Pulling from the Table 4 Information and the RefGenes table to get the class information

supplemental4 <- read.csv("Supplemental_Table_4_v2.csv", header = TRUE)
refgenes_AMR <- read.csv("refgenes.csv")
refgenes_AMR <- refgenes_AMR %>% filter(Type == "AMR")

argdata <- left_join(supplemental4, refgenes_AMR, by = c("code3" = "RefSeq.nucleotide"))


## reformatting
library(dplyr)

argdata$readCount <- as.numeric(argdata$readCount)

argdata$Source <- ifelse(grepl("HUM",argdata$SAMPLE_ID), "Human","Lemur")

RPKM_class_sum <- argdata %>% group_by(SAMPLE_ID, Class, Source) %>% dplyr::select(-X) %>% summarise(sumTemplate = sum(template_length_kb), sumReads = sum(readCount), number_rooted_reads, RPKM = ((sum(readCount)/(sum(template_length_kb)*number_rooted_reads))*1000000000)) %>% unique()

## creating the input count matrix by the class: 
library(tidyr)
ARG_class_counts <- RPKM_class_sum %>% ungroup() %>% dplyr::select(SAMPLE_ID, Class, sumReads) %>% pivot_wider(names_from = SAMPLE_ID, values_from = sumReads, values_fill = 0)

ARG_class_counts <- tibble::column_to_rownames(ARG_class_counts, "Class")

# creating the group vector
ARG_class_groups <- RPKM_class_sum %>% ungroup(Class) %>% dplyr::select(Source) %>% unique() %>% ungroup() %>% dplyr::select(Source) 

ARG_class_groups <- as.vector(ARG_class_groups$Source)
```

# By Genes - Data
```{r}


RPKM_genefamily_sum <- argdata %>% group_by(SAMPLE_ID, Gene.family, Source) %>% dplyr::select(-X) %>% summarise(sumTemplate = sum(template_length_kb), sumReads = sum(readCount), number_rooted_reads, RPKM = ((sum(readCount)/(sum(template_length_kb)*number_rooted_reads))*1000000000)) %>% unique()

## creating the input count matrix by the gene: 
library(tidyr)
ARG_gf_counts <- RPKM_genefamily_sum %>% ungroup() %>% dplyr::select(SAMPLE_ID, Gene.family, sumReads) %>% pivot_wider(names_from = SAMPLE_ID, values_from = sumReads, values_fill = 0)

ARG_gf_counts <- tibble::column_to_rownames(ARG_gf_counts, "Gene.family")

# creating the group vector
ARG_gf_groups <- RPKM_genefamily_sum %>% ungroup(Gene.family) %>% dplyr::select(Source) %>% unique() %>% ungroup() %>% dplyr::select(Source) 

ARG_gf_groups <- as.vector(ARG_gf_groups$Source)
```

# By Gene - Run ALDEx2

```{r}

## Run CLR Function, introducing the uncertainty which would be an assumption of half or double the amount of difference implied by normalization
gf.clr <- aldex.clr(ARG_gf_counts, ARG_gf_groups, gamma = 0.5, denom = "all")

## Generate effect plot to incorporate confidence intervals for both the effect size and the t-tests/ranks
gf.effect <- aldex.effect(gf.clr, CI=T, verbose=F, include.sample.summary=F,  paired.test=FALSE)
gf.tt <- aldex.ttest(gf.clr, hist.plot=F, paired.test=FALSE, verbose=FALSE)
gf.all <- data.frame(gf.tt,gf.effect)
  
## Plots that demonstrate the differential abundance with CI 
sgn <- sign(gf.effect$effect.low) == sign(gf.effect$effect.high)
par(mfrow=c(1,2))
plot(gf.effect$rab.all, gf.effect$diff.btw, pch=19, cex=0.3, col="grey", xlab="Abundance", ylab="Difference", main="Bland-Altman")
points(gf.effect$rab.all[abs(gf.effect$effect) >=2], gf.effect$diff.btw[abs(gf.effect$effect) >=2], pch=19, cex=0.5, col="red")
points(gf.effect$rab.all[sgn], gf.effect$diff.btw[sgn], cex=0.7, col="blue")

plot(gf.effect$diff.win, gf.effect$diff.btw, pch=19, cex=0.3, col="grey",xlab="Dispersion", ylab="Difference", main="Effect")
points(gf.effect$diff.win[abs(gf.effect$effect) >=2], gf.effect$diff.btw[abs(gf.effect$effect) >=2], pch=19, cex=0.5, col="red")
points(gf.effect$diff.win[sgn], gf.effect$diff.btw[sgn], cex=0.7, col="blue")
abline(0,2, lty=2, col="grey")
abline(0,-2, lty=2, col="grey")


library(ggplot2)

## Making a dataframe with the p-values from both the Welshe's test and wilcox
library(dplyr)

ARG_gf_res <- gf.all %>% tibble::rownames_to_column(var = "GeneFamily")

ARG_gf_res_wel <- ARG_gf_res %>% dplyr::select(GeneFamily, we.eBH) %>% mutate(test = "Welch") 
colnames(ARG_gf_res_wel)[2] <- "P_val"

ARG_gf_res_wil <- ARG_gf_res %>% dplyr::select(GeneFamily, wi.eBH) %>% mutate(test = "Wilcox")
colnames(ARG_gf_res_wil)[2] <- "P_val"
ARG_gf_pvals <- rbind(ARG_gf_res_wil, ARG_gf_res_wel)

ggplot(ARG_gf_pvals, aes(y =  reorder(GeneFamily,-P_val), x = P_val, color = test)) + geom_point() +
  scale_color_manual(values = c("#767EFF","#000666")) + 
  geom_vline(xintercept = 0.05, linetype = "dashed", color = "grey78") + 
  labs(y = "Gene Family", x = "Adjusted P-value", color = "Test")

###

## with

sgn <- sign(gf.effect$effect.low) == sign(gf.effect$effect.high)
#gf.all <- gf.all %>% tibble::rownames_to_column(var = "GeneFamily")

par(mfrow=c(1,3))
aldex.plot(gf.all, type="MA", test="welch", xlab="Log-ratio abundance",
    ylab="Difference", main='Bland-Altman plot', all.cex = 0.8, called.cex = 0.9, called.pch = 17, rare.cex = 0.9)
points(gf.all$rab.all[abs(gf.all$effect) >=2], gf.all$diff.btw[abs(gf.all$effect) >=2], pch=17, cex=0.9, col="red")
points(gf.all$rab.all[sgn], gf.all$diff.btw[sgn], pch =2,  cex=1.1, col="blue")
text(gf.all$rab.all[sgn], gf.all$diff.btw[sgn], labels=gf.all$GeneFamily[sgn], cex= 0.7, pos = 3)

aldex.plot(gf.all, type="MW", test="welch", xlab="Dispersion",
    ylab="Difference", main='Effect plot', all.cex = 0.8, called.cex = 0.9, called.pch = 17, rare.cex = 0.9)
points(gf.all$diff.win[abs(gf.all$effect) >=2], gf.all$diff.btw[abs(gf.all$effect) >=2], pch=17, cex=0.9, col="red")
points(gf.all$diff.win[sgn], gf.all$diff.btw[sgn], pch = 2, cex=1.1, col="blue")
text(gf.all$diff.win[sgn], gf.all$diff.btw[sgn], labels=gf.all$GeneFamily[sgn], cex= 0.7)

p.add <- min(gf.all$we.eBH[gf.all$we.eBH > 0])/10
all.p <- gf.all$we.eBH + p.add
gf.all$log10 <- -1 * log10(all.p)

aldex.plot(gf.all, type="volcano", test="welch", xlab="Difference",
    ylab="-1(log10(q))", main='Volcano plot', all.cex = 0.8, called.cex = 0.9, called.pch = 17, rare.cex = 0.9)
points(gf.all$diff.btw[sgn], gf.all$log10[sgn], pch = 2, cex=1.1, col="blue")
text(gf.all$diff.btw[sgn], gf.all$log10[sgn], labels=gf.all$GeneFamily[sgn], cex= 0.7, pos = 3)



######
sgn <- sign(gf.effect$effect.low) == sign(gf.effect$effect.high)
par(mfrow=c(1,2))
plot(gf.effect$rab.all, gf.effect$diff.btw, pch=19, cex=0.3, col="grey", xlab="Abundance", ylab="Difference", main="Bland-Altman")
points(gf.effect$rab.all[abs(gf.effect$effect) >=2], gf.effect$diff.btw[abs(gf.effect$effect) >=2], pch=19, cex=0.5, col="red")
points(gf.effect$rab.all[sgn], gf.effect$diff.btw[sgn], cex=0.7, col="blue")

plot(gf.effect$diff.win, gf.effect$diff.btw, pch=19, cex=0.3, col="grey",xlab="Dispersion", ylab="Difference", main="Effect")
points(gf.effect$diff.win[abs(gf.effect$effect) >=2], gf.effect$diff.btw[abs(gf.effect$effect) >=2], pch=19, cex=0.5, col="red")
points(gf.effect$diff.win[sgn], gf.effect$diff.btw[sgn], cex=0.7, col="blue")
abline(0,2, lty=2, col="grey")
abline(0,-2, lty=2, col="grey")


##corrected p-value for Wilcox test
ggplot(ARG_gf_res, aes(y =  reorder(GeneFamily,-wi.eBH), x = wi.eBH)) + geom_point() + geom_vline(xintercept = 0.05, linetype = "dashed", color = "grey78") + 
  labs(y = "Gene Family")

ggplot(ARG_gf_res, aes(y =  reorder(GeneFamily,rab.win.Human), x = rab.win.Human)) +
  geom_bar(stat= "identity") + 
  labs(y = "Gene Family", x = "Median clr for humans")


```

# Effect size and Sensitivity test by class 
```{r}

## Supplemental figure to demonstrate the sensitivity testing of scaling and the impact of effect size on predicting outcomes; 

## Testing the appropriate gamma to select: 
gamma_to_test <- c(1e-3, .1, .25, .5, .75, 1, 2, 3, 4, 5)

##Run the CLR function
clr_class <- aldex.clr(ARG_class_counts, ARG_class_groups)

##Run the CLR function
clr_class <- aldex.clr(ARG_class_counts, ARG_class_groups)
clr_class_g1 <- aldex.clr(ARG_class_counts, ARG_class_groups, gamma = 1, denom = "all")

## Check effect size measures

class.effect <- aldex.effect(clr_class_g1, CI=T, verbose=F,  paired.test=FALSE)
class.tt <- aldex.ttest(clr_class_g1, hist.plot=F, paired.test=FALSE, verbose=FALSE)
class.all <- data.frame(class.tt,class.effect)
  
par(mfrow=c(1,2))
aldex.plot(class.all, type="MA", test="welch", main='MA plot')
aldex.plot(class.all, type="MW", test="welch", main='effect plot')

sgn <- sign(class.effect$effect.low) == sign(class.effect$effect.high)
par(mfrow=c(1,2))
plot(class.effect$rab.all, class.effect$diff.btw, pch=19, cex=0.3, col="grey", xlab="Abundance", ylab="Difference", main="Bland-Altman")
points(class.effect$rab.all[abs(class.effect$effect) >=2], class.effect$diff.btw[abs(class.effect$effect) >=2], pch=19, cex=0.5, col="red")
points(class.effect$rab.all[sgn], class.effect$diff.btw[sgn], cex=0.7, col="blue")

plot(class.effect$diff.win, class.effect$diff.btw, pch=19, cex=0.3, col="grey",xlab="Dispersion", ylab="Difference", main="Effect")
points(class.effect$diff.win[abs(class.effect$effect) >=2], class.effect$diff.btw[abs(class.effect$effect) >=2], pch=19, cex=0.5, col="red")
points(class.effect$diff.win[sgn], class.effect$diff.btw[sgn], cex=0.7, col="blue")
abline(0,2, lty=2, col="grey")
abline(0,-2, lty=2, col="grey")


## run CLR function on class data
clr_class <- aldex.clr(ARG_class_counts, ARG_class_groups)


##Run sensitivity analysis function
sen_res_class <- aldex.senAnalysis(clr_class, gamma = gamma_to_test)
plotGamma(sen_res_class)


##Run the CLR function
clr_gf <- aldex.clr(ARG_gf_counts, ARG_gf_groups)

##Run sensitivity analysis function
sen_res_gf <- aldex.senAnalysis(clr_gf, gamma = gamma_to_test)
gf_effectsize <- plotGamma(sen_res_gf)[[2]]
gf_sensitivity <- plotGamma(sen_res_gf)[[1]]
class_effectsize <- plotGamma(sen_res_class)[[2]]
class_sensitivity <- plotGamma(sen_res_class)[[1]] 

library(cowplot)
plot_grid(gf_sensitivity, gf_effectsize, class_sensitivity, class_effectsize, labels = "auto", rel_widths = c(0.5,0.5,1,1), rel_heights = c(0.5,0.5,1,1))

```

